# Initialise 3 mongo containers from the same image

mongo3:
  hostname: mongo3
  image: mongo:latest
  command: mongod --replSet my-mongo-set --rest
  ports:
    - "30003:27017"
  restart: always

mongo2:
  hostname: mongo2
  image: mongo:latest
  command: mongod --replSet my-mongo-set --rest
  ports:
    - "30002:27017"
  restart: always

mongo1:
  hostname: mongo1
  image: mongo:latest
  command: mongod --replSet my-mongo-set --rest
  ports:
    - "30001:27017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  restart: always


# This configures the MongoDB replicaset
mongosetup:
  image: mongo:latest
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/mongosetup.sh" ]


