version: '2'

# Initialise 5 mongo containers from the same image
services:
  mongo5:
    hostname: mongo5
    image: mongo:3.2
    command: mongod --replSet my-mongo-set --rest --httpinterface
    ports:
      - "30005:27017"
    restart: always

  mongo4:
    hostname: mongo4
    image: mongo:3.2
    command: mongod --replSet my-mongo-set --rest --httpinterface
    ports:
      - "30004:27017"
    restart: always

  mongo3:
    hostname: mongo3
    image: mongo:3.2
    command: mongod --replSet my-mongo-set --rest --httpinterface
    ports:
      - "30003:27017"
    restart: always

  mongo2:
    hostname: mongo2
    image: mongo:3.2
    command: mongod --replSet my-mongo-set --rest --httpinterface
    ports:
      - "30002:27017"
    restart: always

  mongo1:
    hostname: mongo1
    image: mongo:3.2
    command: mongod --replSet my-mongo-set --rest --httpinterface
    ports:
      - "30001:27017"
    links:
      - mongo2:mongo2
      - mongo3:mongo3
      - mongo4:mongo4
      - mongo5:mongo5
    restart: always

  # This configures the MongoDB replicaset
  mongosetup:
    image: mongo:latest
    links:
      - mongo1:mongo1
      - mongo2:mongo2
      - mongo3:mongo3
      - mongo4:mongo4
      - mongo5:mongo5
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongosetup.sh" ]
